### ISSUE TITLE
Release as steam app?

### ISSUE THREAD

**Issue by alxspiker** [Frietvorkje69/DeckHub#3]
I was looking into the documentation, if we compile the website as a linux/windows app you should be able to release as an actual app on the steam store. Note I only mention windows support for the ROG Ally and Legion Go.

https://partner.steamgames.com/doc/sdk/uploading

### How much does it cost to publish an app on Steam?
Publishing an app on Steam requires a one-time fee of $100. This fee is nonrefundable but can be recouped if your app generates at least $1,000 in adjusted gross revenue from the Steam Store and in-app purchases.

**Comment by alxspiker** [comment]
If it is released as a steam app, you might have to exclude the "Illegal" services or just allow people to add those services back to the LocalStorage themselves through the UI in a Add Service form.

**Comment by Frietvorkje69** [comment]
I find the idea intriguing. However, I believe that releasing the application as a downloadable via GitHub, perhaps through Discover for Linux, might be a more straightforward approach to take. Releasing it as a Steam app could potentially introduce unneeded complications, I'm not sure.

**Comment by alxspiker** [comment]
Made an executable version so it launches on my Ally. Might start adding some features like getting the battery percent and time and such. 

![Photoleap_10_04_2024_08_26_09_c0ZYS](https://github.com/Frietvorkje69/DeckHub/assets/7357054/1c582acf-f78c-42ef-b524-c80c862f82ff)

**Comment by alxspiker** [comment]
If we made a cross platform version, we could potentially launch on steam which makes it easily available to all devices. Turn it into a full blown launcher which can sync themes and such between devices. Would love to have one interface on all my different Handheld consoles.

**Comment by Frietvorkje69** [comment]
Could be worth looking into now that all the necessary features (that I can think of) are included!
